### ISSUE TITLE
Rescheduling succesfull but nothing actually was scheduled

### ISSUE THREAD

**Issue by iluvatar1** [dvalbuena1/visa_rescheduler_aws#1]
Hi, I have been using this scheduler and recently it send me the notification of succesfull reschedule but actually nothing changed. How can I trace the possible bug? 
I use it locally (google chrome driver). 
Here is what I got:
![image](https://user-images.githubusercontent.com/1454267/213257446-d076b70c-5c19-43e9-81e0-a363ba9c05b5.png)
Thanks for the useful tool...

**Comment by iluvatar1** [comment]
Hola, para complementar, los únicos cambios que hice fueron lo siguientes:

- Este lo hice por arreglar un error cuando no era con grupo, un dia me encontro una fecha pero fallo ahi
![image](https://user-images.githubusercontent.com/1454267/213326350-04d83c47-e61f-4526-b957-1ac06948be37.png)

- Este fue para hacerlo funcionar en linux con la opcion headless para poder ejecutarlo desde consola
![image](https://user-images.githubusercontent.com/1454267/213326385-a55474b2-2cd1-43ef-a784-c2694381ded3.png)


Lo que me causa curiosidad es que el mensaje de Reschedule succesful solamente se da cuando el servidor retorna codigo 200, entonces no se que pudo pasar porque la cita como tal no fue modificada.

De nuevo gracias por la herramienta. Si debo poner algo en el codigo para rastrear el error, con gusto lo hago. Soy muy novato en esto de html y javascript y selenium

**Comment by dvalbuena1** [comment]
Un comportamineto algo extraño. 
Le recomendaria analizar el request de respuesta que esta generando el servidor, ya que pude no ser un error del programa como tal.
En ese caso puede añadir un log como se muestra en el codigo.
```
 r = requests.post(APPOINTMENT_URL, headers=headers, data=data)
 if r.status_code == 200:
     logger.info(f"Request message: {r.text}")
     msg = f"Rescheduled Successfully! {date} {time}" + f", ASC: {asc_date} {asc_time}" if NEED_ASC else ""
     self.send_notification(msg)
     return Result.SUCCESS
```
En caso de no volverse a presentar el problema notificarlo en este hilo.

Adicional se realizo la correccion en caso de ser un solo solicitante.   9329f5d0a9a185cf45af8781e03ac38f82d54019

**Comment by iluvatar1** [comment]
Notifico que funciona, gracias
