### ISSUE TITLE
Script cant locate a path while rescheduling

### ISSUE THREAD

**Issue by efecnc** [dvalbuena1/visa_rescheduler_aws#15]
**Sending notification crashes and rescheduling is not working; rescheduling solution solution seems easy but I was not able to fix it could you please help me, here is my log:**

INFO:do_login_action -  login successful!
INFO:print_dates - Available dates:
INFO:print_dates - 2024-03-12    business_day: True
INFO:print_dates - 2024-03-26    business_day: True
INFO:print_dates - 2024-03-28    business_day: True
INFO:print_dates - 2024-04-01    business_day: True
INFO:print_dates - 2024-04-03    business_day: True
INFO:get_available_date - Checking for an earlier date:
INFO:is_earlier - Is 2024-11-08 00:00:00 > 2024-03-12 00:00:00: True
INFO:get_time - Got time successfully! 2024-03-12 09:00
INFO:main - New date: 2024-03-12 09:00
INFO:reschedule - Starting Reschedule (2024-03-12)
INFO:reschedule -       multiple applicants
INFO:send_notification - Sending notification: HELP! Crashed.
**ERROR:main - Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="utf8"]"}**

**I Believe here is the problem:**
data = {
            **"utf8": self.driver.find_element(by=By.NAME, value='utf8').get_attribute('value'),**
            "authenticity_token": self.driver.find_element(by=By.NAME, value='authenticity_token').get_attribute(
                'value'),
            "confirmed_limit_message": self.driver.find_element(by=By.NAME,
                                                                value='confirmed_limit_message').get_attribute(
                'value'),
            "use_consulate_appointment_capacity": self.driver.find_element(by=By.NAME,
                                                                           value='use_consulate_appointment_capacity').get_attribute(
                'value'),
            "appointments[consulate_appointment][facility_id]": FACILITY_ID,
            "appointments[consulate_appointment][date]": date,
            "appointments[consulate_appointment][time]": time,
        }

**Comment by AlbertiPot** [comment]
same issue

**Comment by Ravi-099** [comment]
I was able to run this script by skipping the below line. It looks like the website doesn't use this element. I was able to reschedule it but it seems like the notification feature doesn't work anymore. 

Before
```
        data = {
            "utf8": self.driver.find_element(by=By.NAME, value='utf8').get_attribute('value'),
            "authenticity_token": self.driver.find_element(by=By.NAME, value='authenticity_token').get_attribute(
                'value'),
```

After
```
        data = {
            # "utf8": self.driver.find_element(by=By.NAME, value='utf8').get_attribute('value'),
            "authenticity_token": self.driver.find_element(by=By.NAME, value='authenticity_token').get_attribute(
                'value'),
```

**Comment by dvalbuena1** [comment]
As mentioned in this other issue https://github.com/dvalbuena1/visa_rescheduler_aws/issues/10#issuecomment-1813712967, the problem is now solved
