### ISSUE TITLE
Does this find the earliest possible reschedule date

### ISSUE THREAD

**Issue by kchaya1** [dvalbuena1/visa_rescheduler_aws#17]
When the dates are returned from the site, do they come in ascending order? If not, we should really sort the dates before searching through them, that way we find the earliest possible reschedule date right?

**Comment by dvalbuena1** [comment]
This is an example of the first 5 dates when trying to retrieve the available dates

```
INFO:print_dates - 2024-10-21    business_day: True
INFO:print_dates - 2024-11-18    business_day: True
INFO:print_dates - 2025-04-07    business_day: True
INFO:print_dates - 2025-07-14    business_day: True
INFO:print_dates - 2025-10-16    business_day: True
```

So there is no need to order them
