### ISSUE TITLE
Earlier date found, but rescheduling failed on mexican visa site since it couldn't find a css element named "utf8"

### ISSUE THREAD

**Issue by kchaya1** [dvalbuena1/visa_rescheduler_aws#19]
I am more of a backend developer so I apologize if i use some incorrect frontend terms here, but I encountered a problem where an earlier date was found, but then it failed to find a element named utf8.

I believe this line of code is the culprit:
https://github.com/dvalbuena1/visa_rescheduler_aws/blob/main/visa.py#L185

I did a chrome inspect on the page where the appointment is rescheduled, the one referred to in the URL here:
https://github.com/dvalbuena1/visa_rescheduler_aws/blob/main/visa.py#L58

And I  tried to find all the elements in this block of the code using the "elements" section in chrome devtools
https://github.com/dvalbuena1/visa_rescheduler_aws/blob/main/visa.py#L184-L203

I was able to find every single one EXCEPT for the utf8 element referred to here, so it must have been removed.
However, it looks like "utf8" is a parameter in the body of the post request used to reschedule the appointment.

**My main question is:**
What should the value of this utf8 parameter be in the body of the reschedule request? Has anyone successfully made a call to the reschedule API that can tell me what it should be? All the current appointment dates are much much later than the one that is there rn, so I don't want to reschedule it to those later dates just to see what the parameter in the body should be. Appointments are very scarce right now, and I don't want to risk putting in the wrong value for the parameter and thus missing the opportunity for an earlier appointment.

**Comment by dvalbuena1** [comment]
https://github.com/dvalbuena1/visa_rescheduler_aws/issues/10#issuecomment-1813712967
As mentioned in this comment, the fix has just been made.
