### ISSUE TITLE
Error Aws-Lambda 

### ISSUE THREAD

**Issue by Eljeff13** [dvalbuena1/visa_rescheduler_aws#25]
Hola @dvalbuena1, al implementar la funcion, subirla a aws-lambda y correrla se estan presentado el siguiente error:

[ERROR] Error: unsupported locale setting
Traceback (most recent call last):

**Comment by Alefig12** [comment]
@Eljeff13 Estoy teniendo el mismo problema, cómo lo solucionaste?

**Comment by Eljeff13** [comment]
Cambiando la versión de Python que le ingreso a la función.
