### ISSUE TITLE
Appointment not change even after got 200 response

### ISSUE THREAD

**Issue by jyepesr1** [dvalbuena1/visa_rescheduler_aws#3]
I got the following message

```
INFO:print_dates - Available dates:
INFO:print_dates - 2023-04-17    business_day: True
INFO:print_dates - 2025-03-03    business_day: True
INFO:print_dates - 2025-03-05    business_day: True
INFO:print_dates - 2025-05-12    business_day: True
INFO:print_dates - 2025-07-16    business_day: True
INFO:get_available_date - Checking for an earlier date:
INFO:is_earlier - Is 2024-03-13 00:00:00 > 2023-04-17 00:00:00: True
INFO:get_time - Got time successfully! 2023-04-17 11:00
INFO:main - New date: 2023-04-17 11:00
INFO:asc_availability - ASC Availability
INFO:get_time - Got time successfully! 2023-04-10 15:45
INFO:reschedule - Starting Reschedule (2023-04-17)
INFO:reschedule -       single applicant
INFO:send_notification - Sending notification: Rescheduled Successfully! 2023-04-17 11:00, ASC: 2023-04-10 15:45
```

The issue is I checked the account and the appointment was not modified

**Comment by dvalbuena1** [comment]
You are right, there seems to have been a 200 response.
Most likely it was a problem with their server, not the program because it has already happened to someone else #1 . Is this the first time this has happened or has it been happening often?
In addition, if you make any important changes to the code, please share it.

**Comment by iluvatar1** [comment]
This has happened again to me four times in the last two days, using the code without any changes. I got 200 status but nothing is changed on the appointment system

**Comment by iluvatar1** [comment]
By the way, I am running with the local option, not aws. I installed all the recommended requirements

**Comment by jyepesr1** [comment]
I'm running on my local as well, but I haven't seen any other spot for now, so I haven't been able to reproduce the error. @iluvatar1 has you been able to schedule an appointment correctly even after those false 200?

I'm going to deploy the lambda and will update this issue once I got another false 200.

**Comment by dvalbuena1** [comment]
As already mentioned @jyepesr1, my recommendation is to use it from another machine or use lambda, since it is possible that using the same IP always, they may be blocking the request.
