### ISSUE TITLE
Cooldown (Discussion)

### ISSUE THREAD

**Issue by juanzgc** [dvalbuena1/visa_rescheduler_aws#5]
How often are you hitting the Cooldown period, in which you don't get any dates? It seems once cooldown has begun, at a minimum must wait 4 hours. 

And have you been able to successfully get a new Consulate date? ASC dates are very available, but the consulate dates are not... Currently earliest is showing `2025-08-06`

**Comment by JesseWest7** [comment]
In my opinion, the script will trigger cooling after 4 hours of running. I don't know if there's a certain amount of time between each execution that doesn't trigger a cooldown, or if it definitely does after 4 hours

**Comment by dvalbuena1** [comment]
There will be a ban if you exceute the script very often. Check this issue https://github.com/uxDaniel/visa_rescheduler/issues/4
For this reason, it is recommended to trigger it every 10 minutes.

**Comment by JesseWest7** [comment]
Thank you for your reply. When I set the interval time to 601S for the first time, 13H didn't trigger cooling. However, when I ran it again today, a cooling period of 5H would still be triggered around 4H.
And should I change my IP on a regular basis? At present, I am not clear on what basis the website triggers the cooling off period. After running for a long time, 20S and 601S will trigger the cooling off period around 4H.

**Comment by dvalbuena1** [comment]
It is difficult to know what the reason may be. But I think it could be at the IP level as you mention or directly at the account level. Since dictating multiple attempts with the same session can temporarily block it.

From my point of view to avoid any problems, it is better just to increase the time.
